name: Build and Deploy Dioxus App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust and WASM target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
          components: rustfmt, clippy

      - name: Install Dioxus CLI
        run: cargo install dioxus-cli

      - name: Build Dioxus app
        run: dx build --release

      - name: Debug file structure
        run: |
          ls -R target/wasm32-unknown-unknown/release/
          ls -R dist/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact-name: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
